version: "3.5"

services:
  db_auth: 
    container_name: DB_API
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=greenbit
      - POSTGRES_USER=admin
    image: postgres:15.5-alpine3.18